// This file is automatically generated. Do not edit it directly.

// Your Opix credentials
export const CLIENT_ID = "7562d96e2a5159daf06196efb8dbf565";
export const API_KEY = "opx_299ef4625e9dfb1baa2101a794f9ddad63be08f0be7f0cacc2d8fd1eb4c30479";

// Import your Opix SDK factory
import { createClient } from "./sdk";

// Import the Opix client like this:
// import { opix } from "@/integrations/opix/client";

export const opix = createClient(CLIENT_ID, API_KEY);
